minor_changes:
  - "default callback plugin - add option to configure line width for YAML output. This allows to disable line wrapping
     (https://github.com/ansible/ansible/issues/84657, https://github.com/ansible/ansible/pull/85498)."
