bugfixes:
  - >-
    ``ansible-galaxy install``/``ansible-galaxy collection download`` - collections from git repositories
    with a tag or sha version no longer emit detached head warning messages
    (https://github.com/ansible/ansible/issues/86169).
